<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'tFPDF' => array($vendorDir . '/rev42/tfpdf/src'),
    'dflydev\\markdown' => array($vendorDir . '/dflydev/markdown/src'),
    'Twig_Extensions_' => array($vendorDir . '/twig/extensions/lib'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Pimple' => array($vendorDir . '/pimple/pimple/lib'),
    'MaxMind' => array($vendorDir . '/maxmind-db/reader/src'),
    'JsonSerializable' => array($vendorDir . '/geoip2/geoip2/compat'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'GeoIp2' => array($vendorDir . '/geoip2/geoip2/src'),
    '' => array($baseDir . '/bb-library'),
);
